title:              은성 dev
email:              dmstjd1024@naver.com
description:        EunSeong dev blog
author:             Start Bootstrap
baseurl:            "/"
url:                "https://dmstjd1024.github.io"

# Social Profiles
twitter_username:
github_username: dmstjd1024
facebook_username:
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
